language: sh

before_deploy:
  - zip -r laravel.zip laravel
  - zip -r symfony-mysql.zip symfony-mysql.zip

deploy:
  provider: releases
  api_key: ${API_KEY}
  file_glob: true
  file: "*.zip"
  skip_cleanup: true
  on:
    tags: true
